@Secretariat.Api_HostAddress = http://localhost:5244

GET {{Secretariat.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

@Secretariat_Api_HostAddress = https://localhost:7170

POST {{Secretariat_Api_HostAddress}}/api/correspondence
Content-Type: application/json

{
  "type": 2,
  "sender": "Urząd Miasta",
  "subject": "Test korespondencji przychodzącej",
  "receivedDate": "2026-09-01T21:50:00",
  "recipientUserId": 1
}
###



POST {{Secretariat_Api_HostAddress}}/api/correspondence/1/read
###

GET {{Secretariat_Api_HostAddress}}/api/correspondence/1
Accept: application/json

###
PUT {{Secretariat_Api_HostAddress}}/api/correspondence/1
Content-Type: application/json

{
  "number": "TEST/2026/001",
  "sender": "Firma Testowa Sp. z o.o.",
  "subject": "Zaktualizowane zapytanie ofertowe",
  "receivedDate": "2026-08-31T20:20:00"
}

###


POST {{Secretariat_Api_HostAddress}}/api/correspondence
Content-Type: application/json

{
  "sender": "Urząd Miasta",
  "subject": "Dokument testowy dla Jana Kowalskiego",
  "receivedDate": "2026-09-01T20:45:00",
  "recipientUserId": 1
}

###

POST {{Secretariat_Api_HostAddress}}/api/correspondence/1/attachments
Content-Type: multipart/form-data; boundary=MyBoundary


Content-Disposition: form-data; name="file"; filename="test.pdf"
Content-Type: application/pdf

< ./test.pdf
