@Secretariat.Api_HostAddress = http://localhost:5244

GET {{Secretariat.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

@Secretariat_Api_HostAddress = https://localhost:7170

POST {{Secretariat_Api_HostAddress}}/api/correspondence
Content-Type: application/json

{
  "number": "TEST/2026/001",
  "sender": "Firma Testowa",
  "subject": "Zapytanie ofertowe",
  "receivedDate": "2026-08-31T20:20:00"
}
###

GET {{Secretariat_Api_HostAddress}}/api/correspondence
Accept: application/json