@Secretariat.Api_HostAddress = http://localhost:5244

GET {{Secretariat.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

@Secretariat_Api_HostAddress = https://localhost:7170

POST {{Secretariat_Api_HostAddress}}/api/correspondence
Content-Type: application/json

{
  "type": 2,
  "sender": "Urząd Miasta",
  "subject": "Test korespondencji przychodzącej",
  "receivedDate": "2026-09-01T21:50:00",
  "recipientUserId": 1
}
###



POST {{Secretariat_Api_HostAddress}}/api/correspondence/1/read
###

GET {{Secretariat_Api_HostAddress}}/api/correspondence
X-User-Id: 1
Accept: application/json

###
PUT {{Secretariat_Api_HostAddress}}/api/correspondence/1
Content-Type: application/json

{
  "number": "TEST/2026/001",
  "sender": "Firma Testowa Sp. z o.o.",
  "subject": "Zaktualizowane zapytanie ofertowe",
  "receivedDate": "2026-08-31T20:20:00"
}

###
GET {{Secretariat_Api_HostAddress}}/api/correspondence
X-User-Id: 3
Accept: application/json
###

POST {{Secretariat_Api_HostAddress}}/api/appusers
Content-Type: application/json

{
  "displayName": "Adam Pracownik",
  "email": "adam.pracownik@firma.pl",
  "role": 1
}

###
POST {{Secretariat_Api_HostAddress}}/api/correspondence
Content-Type: application/json

{
  "type": 1,
  "sender": "Firma Testowa",
  "subject": "Dokument dla Adama",
  "receivedDate": "2026-09-06T17:30:00",
  "recipientUserId": 3
}
###

GET {{Secretariat_Api_HostAddress}}/api/internal-correspondence
X-User-Id: 3
Accept: application/json


###
POST {{Secretariat_Api_HostAddress}}/api/correspondence
Content-Type: application/json

{
  "type": 2,
  "sender": "Sekretariat",
  "subject": "Odpowiedź na pismo",
  "receivedDate": "2026-09-06T17:45:00",
  "recipientUserId": 3,
  "relatedIncomingCorrespondenceId": 10
}

###


POST {{Secretariat_Api_HostAddress}}/api/internal-correspondence
X-User-Id: 3
Content-Type: application/json

{
  "subject": "Zakup nowych komputerów",
  "description": "Prośba o akceptację zakupu nowych komputerów do działu IT."
}

### Lista użytkowników

GET {{Secretariat_Api_HostAddress}}/api/appusers
Accept: application/json



### Dodanie drugiego akceptującego

POST {{Secretariat_Api_HostAddress}}/api/appusers
Content-Type: application/json

{
  "displayName": "Anna Akceptująca",
  "email": "anna.akceptujaca@example.com",
  "entraObjectId": null,
  "role": 2
}

### TEST: nowy dokument do sprawdzenia odrzucenia

POST {{Secretariat_Api_HostAddress}}/api/internal-correspondence
X-User-Id: 3
Content-Type: application/json

{
  "subject": "Zakup wyposażenia biurowego",
  "description": "Dokument testowy do sprawdzenia procesu odrzucania.",
  "approverUserIds": [5, 6]
}

### TEST: szczegóły dokumentu z dwoma akceptującymi

GET {{Secretariat_Api_HostAddress}}/api/internal-correspondence/4
X-User-Id: 3
Accept: application/json


### TEST: Piotr zatwierdza dokument nr 4

POST {{Secretariat_Api_HostAddress}}/api/internal-correspondence/4/approve
X-User-Id: 5
Accept: application/json



### TEST: sprawdzenie statusów po akceptacji Piotra

GET {{Secretariat_Api_HostAddress}}/api/internal-correspondence/4
X-User-Id: 3
Accept: application/json



### TEST: Anna zatwierdza dokument nr 4

POST {{Secretariat_Api_HostAddress}}/api/internal-correspondence/4/approve
X-User-Id: 6
Accept: application/json



### TEST: dokument po zatwierdzeniu przez obie osoby

GET {{Secretariat_Api_HostAddress}}/api/internal-correspondence/4
X-User-Id: 3
Accept: application/json



### TEST: Anna odrzuca dokument nr 5

POST {{Secretariat_Api_HostAddress}}/api/internal-correspondence/5/reject
X-User-Id: 6
Accept: application/json



### TEST: szczegóły odrzuconego dokumentu

GET {{Secretariat_Api_HostAddress}}/api/internal-correspondence/5
X-User-Id: 3
Accept: application/json





### TEST 1: Piotr próbuje zaakceptować odrzucony dokument
### Oczekiwany wynik: 409 Conflict

POST {{Secretariat_Api_HostAddress}}/api/internal-correspondence/5/approve
X-User-Id: 5
Accept: application/json


###

### TEST 2: zwykły pracownik próbuje zatwierdzić dokument
### Oczekiwany wynik: 403 Forbidden

POST {{Secretariat_Api_HostAddress}}/api/internal-correspondence/5/approve
X-User-Id: 3
Accept: application/json